framework:
  messenger:
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      'App\Message\NotifyUserMessage': async
      'App\Domain\Member\Message\UserRegisterMessage': async