framework:
  messenger:
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      App\Infrastructure\Messaging\Message\NotifyUserMessage: async