# Domains Controllers

main_controllers:
    resource: ../../src/Controller/
    type: attribute

admin_controllers:
    resource: ../../src/Domain/Admin/Controller/
    type: attribute

member_controllers:
    resource: ../../src/Domain/Member/Controller/
    type: attribute

post_controllers:
    resource: ../../src/Domain/Member/Controller/
    type: attribute